### PR TITLE
Associate gets working for raymonds purposes

### PR DESCRIPTION
**Pull request by gmckin**
Made sure get associate by email was working correctly.

### CODE REVIEW

**Comment by gmckin** [comment]
Ready to merge

**Review by erchiggins — COMMENTED** [review]
I see a potential problem with the parameter routing. All input parameters for Gets (if we're grabbing that parameter from the url, i.e. "api/controller/id") need to have the same name- whatever you specified in your config file.

**Comment by gmckin** [comment]
modified all controller get methods which take a parameter to use the same parameter and routing style as well as return json rather than xml. Still working with the unit and data controllers which will need to return lists but currently return empty list.

**Comment by gmckin** [comment]
As mentioned in slack, the annotations can be removed easily by Jason and the routes will be as desired.

**Review by erchiggins — APPROVED** [review]

**Pull request merged**
