### PR TITLE
initial branch commit

### PR DESCRIPTION
**Pull request by thonaj**

### CODE REVIEW

**Review by erchiggins — COMMENTED** [review]
Regarding the Post methods: we're not doing anything with the "value" parameter, and the [FromBody] should refer to the incoming object.

**Comment by gmckin** [comment]
When you say that we are not doing anything with "value" do you mean it was merely a placeholder and that it should be replaced with the object being passed in such as the dao object?

**Comment by erchiggins** [comment]
Precisely. It comes free with the template, but there's no reason for it to be there in our code.

**Comment by thonaj** [comment]
ready to merge

**Review by erchiggins — APPROVED** [review]

**Pull request merged**
